name = "Butterium"
author = "BUTR Studios"
version = "v1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "788a686d9aa298c8476181b0c04c50edc0b6d9e0160ea693be4b94691343235b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
