name = "Butterium"
author = "BUTR Studios"
version = "v1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67dc9214839ba107d23f0978d236571ede97a86c19ab8f4132b24c54b9c3ecf5"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
