#Minecraft server properties
#Fri Oct 10 20:36:19 BST 2025
border-color=-13290187
caption-color=-15724528
hide-window-border=true
system-backdrop-type=DWMSBT_NONE
text-color=-1
use-default-border-color=true
use-default-caption-color=false
use-default-text-color=false
use-immersive-dark-mode=true
window-corner-preference=DWMWCP_DEFAULT
